Organizations:
    - &Comprador1
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: Comprador1

        # ID to load the MSP definition as
        ID: Comprador1Msp

        MSPDir: crypto-config/peerOrganizations/comprador1.com/msp

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.comprador1.com
              Port: 11051
