# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # Comprador1
  # ---------------------------------------------------------------------------
  - Name: Comprador1
    Domain: comprador1.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
