# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # Pescador1
  # ---------------------------------------------------------------------------
  - Name: Pescador1
    Domain: pescador1.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
